### ISSUE TITLE
Unable to resolve service error.

### ISSUE THREAD

**Issue by nrkarthick** [EntrypointSoft/AspNet.Identity.EntityFramework6#3]
I followed your code but it gives error as `Unable to resolve service for type 
ApplicationDbContext' while attempting to activate ApplicationUserStore`. Any idea.

**Comment by ghrapan** [comment]
I have added a usage examples, please check the "samples" folder.

**Comment by ghrapan** [comment]
I have made some fixes, please refer to the updated code and samples.

Thanks for reporting.
